# Generated by Django 4.2.26 on 2025-11-29 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_project_technology_alter_contactmessage_is_read_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='mockup_image',
            field=models.ImageField(blank=True, help_text='Project mockup/screenshot', null=True, upload_to='projects/'),
        ),
    ]
